<?php

namespace common\Helper;


class EmailTemplate
{

    // ESS->LEAVE
    const EMAIL_TEMPLATE_LOGIN = "LOGI";
    const EMAIL_TEMPLATE_USER_REGISTERATION = "URNW";
    const EMAIL_TEMPLATE_SAFARI_OPERATOR_REGISTRATION = "STOR";
    const EMAIL_TEMPLATE_BIRDING_OPERATOR_REGISTRATION = "BTOR";
    const EMAIL_TEMPLATE_SAFARI_OPERATOR_FREE_QUOTE = "STOQ";
    const EMAIL_TEMPLATE_ORGANIZE_NEW_SHARE_SAFARI = "ONSR";
    const EMAIL_TEMPLATE_SHARE_SAFARI_REQUEST_CONTACT = "SSRC";
    const EMAIL_TEMPLATE_FOLLOW_REQUEST = "SOFR";
    const EMAIL_TEMPLATE_UNFOLLOW_REQUEST = "SOUR";
    const EMAIL_TEMPLATE_REJECT_SHARE_SAFARI = "TRSS";
}
